### ISSUE TITLE
Approval queue issue

### ISSUE THREAD

**Issue by RickKraut** [phpBB-Studio/AdvancedPointsSystem#4] opened 2019-08-09 07:37 UTC
**Describe the bug**
When a user posts on a forum that has an approval queue, the **"[currency] per forum"** and **"[currency] per group"** will display respective areas of earning points, but the **user account** will **not** display said **earnings**, and will **not receive** them upon post **denial, or approval**. 
_(user also did not earn any points for their post's approval/disapproval, when said option was used.)_

**To Reproduce**
1. Be logged into a user account that has a forum section requiring approval for posts.
2. Post said content.
3. wait for approval.
4. suffer.

**Expected behavior**
User should receive payment.

**Additional suggestion**
User should receive payment for post in said forum based off of a setting, say paid only when post approved.

**additional contents**
May be useful information, settings for the said forum(s) included "per word" and "per character" for topic. (the payment displayed on the graphs in overview displayed the payment properly, user just did not receive them)

**Comment by 3D-I** [comment] 2019-08-09 07:42
Thank you for your contribution. Each request will be examined.

**Comment by mrgoldy** [comment] 2019-08-12 10:15
Thank you for reporting this.
This issue was fixed locally but never got pushed to the actual repository.
The problem is that we check a value with `!empty()` instead of with `isset()`, resulting in that if the user has no points yet, he will not receive any either.

The 'bug' with the charts will be fixed aswell. Those should not yet display the points until the post is approved/disapproved.

Thank you for reporting.

**Closed** 2019-08-16 00:22 UTC
Labels: bug
